import { launch, runWizard, openSubs } from './lib.mjs';
const B = 'http://localhost:4173'; let pass = 0, total = 0;
const check = (n, ok, x = '') => { total++; if (ok) pass++; console.log(ok ? 'PASS' : 'FAIL', n, x); };
const b = await launch();
const p = await (await b.newContext({ viewport: { width: 420, height: 900 }, colorScheme: 'dark' })).newPage();
p.on('dialog', (d) => d.accept()); const errs = []; p.on('pageerror', (e) => errs.push(String(e)));
const submit = async (t) => { await runWizard(p, { text: t }); await p.click('nav button:has-text("Voices")'); await p.waitForSelector('.submission-card'); await openSubs(p); };
await p.goto(B);await p.click('nav button:has-text("Submit")');await p.fill('#auth-email','mark@example.com');await p.click('button:has-text("Send code")');await p.fill('#auth-code','123456');await p.click('button:has-text("Verify")');await p.waitForSelector('#wz-start');
await submit('voice A'); await submit('voice B');
const heading = async () => (await p.locator('h2').first().innerText());
check('starts with 2 real voices', (await heading()).includes('(2)'));
check('cards offer "Mark as test"', (await p.locator('button:has-text("Mark as test")').count()) === 2);
await p.locator('button:has-text("Mark as test")').first().click();
await p.waitForFunction(() => document.querySelectorAll('.submission-card').length === 1);
check('marked card leaves the list (tests hidden)', true);
check('heading counts only what is shown: 1 voice while tests are hidden', (await heading()).includes('(1)') && !(await heading()).includes('test'));
check('toast explains', await p.locator('.toast:has-text("left out of synthesis")').isVisible());
await p.click('.toggle-row:has-text("Show tests")');
check('heading shows 1 real + 1 test once tests are shown', (await heading()).includes('(1 + 1 test)'));
check('card visible again with test badge + "Unmark test"', (await p.locator('.test-card .test-badge').count()) === 1 && (await p.locator('button:has-text("Unmark test")').count()) === 1);
await p.screenshot({ path: 'screens/shot-testflag.png', fullPage: true });
// synthesis tab: real count excludes it, include-tests toggle brings it back
await p.click('nav button:has-text("Home")'); await p.click('.admin-link');
await p.fill('#admin-password', 'letmein'); await p.click('.admin-login button'); await p.waitForSelector('.admin-control');
await p.click('nav button:has-text("Synthesis")');
check('synthesis counts 1 contribution (test excluded)', (await p.locator('button:has-text("Run synthesis")').innerText()).includes('1 contributions'));
await p.click('.toggle-row:has-text("Include test submissions")');
check('include-tests brings it back (2)', (await p.locator('button:has-text("Run synthesis")').innerText()).includes('2 contributions'));
// unmark it again
await p.click('nav button:has-text("Voices")'); await openSubs(p);
if (!(await p.locator('.toggle-row:has-text("Show tests") .toggle.on').count())) await p.click('.toggle-row:has-text("Show tests")');
await p.locator('button:has-text("Unmark test")').click();
await p.waitForFunction(() => !document.querySelector('.test-card'));
check('unmarked: back to 2 real voices', (await heading()).includes('(2)'));
check('no page errors', errs.length === 0, errs.join('|'));
console.log(`\n${pass}/${total} passed`); await b.close();
